# -*- coding: utf-8 -*-
"""chineese_final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1STXQMKN14IyvCl7RjUNGMQVfWkCB0kAI
"""

!pip install easyocr pandas opencv-python

from google.colab import drive
drive.mount('/content/drive')

import os
import pandas as pd
import easyocr

image_dir="/content/drive/MyDrive/Train_images"
output_csv="/content/drive/MyDrive/ocr_datasetchi.csv"

# reader=easyocr.Reader(['en'],gpu=True)
reader = easyocr.Reader(['ch_sim','en'],gpu=True)
data=[]
idx=1

for img in sorted(os.listdir(image_dir)):
    if img.lower().endswith(('.png','.jpg','.jpeg','.webp')):
        path=os.path.join(image_dir,img)
        result=reader.readtext(path,detail=0,paragraph=True)
        text=" ".join(result).replace('\n',' ')
        data.append([idx,img,path,text])
        idx+=1

df=pd.DataFrame(data,columns=["id","image_name","image_path","ocr_text"])
df.to_csv(output_csv,index=False)

print("saved:",output_csv)

import pandas as pd
import re

df_test = pd.read_csv("/content/ocr_datasetchi.csv")

df_test["image_id"] = (
    df_test["image_name"]
    .str.extract(r"(\d+)")
    .astype(int)
)

df_labels = pd.read_excel("/content/Train_labels (2).xlsx")  # id, label
df_labels["id"] = df_labels["id"].astype(int)

df_final = df_test.merge(
    df_labels,
    left_on="image_id",
    right_on="id",
    how="left"
)

df_final = df_final.drop(columns=["id_x", "image_id"])
df_final = df_final[["image_name", "image_path", "ocr_text", "label"]]

# Optional: add a new sequential id column
df_final.insert(0, "id", range(1, len(df_final) + 1))

df_final=df_final.drop(columns=["id"])

df_final["id"] = (
    df_test["image_name"]
    .str.extract(r"(\d+)")
    .astype(int)
)

df_final.head()

df_final.to_csv("final_dataset.csv", index=False)

train_path  = "/content/final_dataset.csv"

# df = pd.read_csv(CSV_PATH, on_bad_lines='skip')

import os, torch, pandas as pd, numpy as np
from PIL import Image
from tqdm import tqdm
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from transformers import CLIPProcessor, CLIPModel

device = "cuda" if torch.cuda.is_available() else "cpu"
processor = CLIPProcessor.from_pretrained("openai/clip-vit-base-patch32")

LABEL_MAP = {
    "Homophobic": 0,
    "Transphobic": 1,
    "Non_Anti_LGBT": 2
}

class MemeDataset(Dataset):
    def __init__(self, csv_file, processor):
        self.df = pd.read_csv(csv_file)
        self.processor = processor

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]

        image_path = row["image_path"]
        text = str(row["ocr_text"])[:300]  # extra safety
        label = LABEL_MAP[row["label"].strip()]

        image = Image.open(image_path).convert("RGB")

        enc = self.processor(
            text=text,
            images=image,
            truncation=True,
            padding="max_length",
            max_length=77,
            return_tensors="pt"
        )

        return {
            "input_ids": enc["input_ids"].squeeze(0),
            "attention_mask": enc["attention_mask"].squeeze(0),
            "pixel_values": enc["pixel_values"].squeeze(0),
            "labels": torch.tensor(label)
        }

train_path = "/content/final_dataset.csv"

device = "cuda" if torch.cuda.is_available() else "cpu"
processor = CLIPProcessor.from_pretrained("openai/clip-vit-base-patch32")
train_ds = MemeDataset(train_path, processor)
train_loader = DataLoader(train_ds, batch_size=16, shuffle=True, num_workers=2)

class MemeHateModel(nn.Module):
    def __init__(self, name="openai/clip-vit-base-patch32"):
        super().__init__()
        self.clip = CLIPModel.from_pretrained(name)
        dim = self.clip.config.projection_dim

        self.classifier = nn.Sequential(
            nn.Linear(dim * 2, 512),
            nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(512, 3)
        )

    def forward(self, input_ids, attention_mask, pixel_values):
        out = self.clip(
            input_ids=input_ids,
            attention_mask=attention_mask,
            pixel_values=pixel_values
        )

        fused = torch.cat([out.image_embeds, out.text_embeds], dim=1)
        return self.classifier(fused)

model = MemeHateModel().to(device)
optimizer = torch.optim.AdamW(model.parameters(), lr=2e-5)
criterion = nn.CrossEntropyLoss()

EPOCHS = 12

for epoch in range(EPOCHS):
    model.train()
    total_loss = 0

    for batch in tqdm(train_loader):
        optimizer.zero_grad()

        for k in batch:
            batch[k] = batch[k].to(device)

        logits = model(
            batch["input_ids"],
            batch["attention_mask"],
            batch["pixel_values"]
        )

        loss = criterion(logits, batch["labels"])
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    print(f"\nEpoch {epoch+1} | Loss: {total_loss/len(train_loader):.4f}")

torch.save(model.state_dict(), "/content/drive/MyDrive/meme_project/lgbtq_meme_model_ee.pt")
print("Model saved ✅")

import os
import pandas as pd
import easyocr

image_dir="/content/drive/MyDrive/Test_images (1)"
output_csv="/content/drive/MyDrive/ocr_test_datasetchi.csv"

# reader=easyocr.Reader(['en'],gpu=True)
reader = easyocr.Reader(['ch_sim','en'],gpu=True)
data=[]
idx=1

for img in sorted(os.listdir(image_dir)):
    if img.lower().endswith(('.png','.jpg','.jpeg','.webp')):
        path=os.path.join(image_dir,img)
        result=reader.readtext(path,detail=0,paragraph=True)
        text=" ".join(result).replace('\n',' ')
        data.append([idx,img,path,text])
        idx+=1

df=pd.DataFrame(data,columns=["id","image_name","image_path","ocr_text"])
df.to_csv(output_csv,index=False)

print("saved:",output_csv)

import pandas as pd
import re

df_test = pd.read_csv("/content/ocr_test_datasetchi.csv")

df_test["image_id"] = (
    df_test["image_name"]
    .str.extract(r"(\d+)")
    .astype(int)
)

df_test.head()

df_final = df_test.drop(columns=["id", "image_name"])
df_final = df_final[["image_id", "image_path", "ocr_text"]]

# Optional: add a new sequential id column
# df_final.insert(0, "id", range(1, len(df_final) + 1))

df_final.to_csv("final_test_dataset.csv", index=False)

df_final.head()

import torch, pandas as pd
from PIL import Image
from tqdm import tqdm
from transformers import CLIPProcessor
import torch.nn as nn
from transformers import CLIPModel

device="cuda" if torch.cuda.is_available() else "cpu"

processor=CLIPProcessor.from_pretrained("openai/clip-vit-base-patch32")

class MemeHateModel(nn.Module):
    def __init__(self,name="openai/clip-vit-base-patch32"):
        super().__init__()
        self.clip=CLIPModel.from_pretrained(name)
        d=self.clip.config.projection_dim
        self.classifier=nn.Sequential(
            nn.Linear(d*2,512),
            nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(512,3)
        )

    def forward(self,input_ids,attention_mask,pixel_values):
        o=self.clip(
            input_ids=input_ids,
            attention_mask=attention_mask,
            pixel_values=pixel_values
        )
        return self.classifier(torch.cat([o.image_embeds,o.text_embeds],1))

model=MemeHateModel().to(device)
model.load_state_dict(torch.load("/content/drive/MyDrive/meme_project/lgbtq_meme_model_ee.pt",map_location=device))
model.eval()

inv={0:"Homophobic",1:"Transphobic",2:"Non_Anti_LGBT"}

def predict(image_path,text):
    image=Image.open(image_path).convert("RGB")
    enc=processor(
        text=str(text)[:300],
        images=image,
        truncation=True,
        padding="max_length",
        max_length=77,
        return_tensors="pt"
    )
    for k in enc:
        enc[k]=enc[k].to(device)
    with torch.no_grad():
        logits=model(
            enc["input_ids"],
            enc["attention_mask"],
            enc["pixel_values"]
        )
    return inv[int(torch.argmax(logits,1))]

CSV_PATH="/content/final_test_dataset.csv"
OUT_PATH="ocr_dataset_predictions.csv"

df=pd.read_csv(CSV_PATH,on_bad_lines="skip")

preds=[]
for _,r in tqdm(df.iterrows(),total=len(df)):
    try:
        preds.append(predict(r["image_path"],r["ocr_text"]))
    except:
        preds.append("ERROR")

df["predicted_label"]=preds
df.to_csv(OUT_PATH,index=False)

print("saved:",OUT_PATH)

df.head()

df = df.sort_values(by="image_id").reset_index(drop=True)

df.to_csv("final_test_dataset111.csv", index=False)

df.head()

dff=pd.read_csv("/content/final_test_dataset111.csv")

import pandas as pd

expected = set(range(1,240))
present = set(dff["image_id"].astype(int))
missing = sorted(expected - present)

missing

df_final = dff.drop(columns=["ocr_text", "image_path"])

df_final.head()

df_final.to_csv("final_test_dataset_chinese.csv", index=False)

dff.head()

import pandas as pd

df2=pd.read_csv("/content/sorted_images.csv")

df2.head()

dff=df2.drop(columns=["id"])

dff.head()

dff["id"] = (
    dff["image_name"]
    .str.extract(r"(\d+)")
    .astype(int)
)

dff.head()

dfx=dff.drop(columns=["image_name"])

dfx.head()

dfxfinal=dfx[['id','predicted_label']]

dfxfinal.to_csv('final_test_dataset_hindi1.csv',index=False)

import pandas as pd

df2=pd.read_csv("/content/test_predictionsff (1).csv")

mp={
    "homophobia":"Homophobia",
    "transphobia":"Transphobia",
    "non_anti_lgbt":"Non_Anti_LGBT"
}

df2["predicted_label"]=df2["predicted_label"].map(mp)

df2.to_csv("output.csv",index=False)

df2.head()

df2["id"] = (
    df2["image_name"]
    .str.extract(r"(\d+)")
    .astype(int)
)

df2.head()

df2 = df2.sort_values(by="id").reset_index(drop=True)

df2.head()

df2=df2[['id','predicted_label']]

df2.head()

df2.to_csv('engfinal.csv',index=False)

df2.head()