# -*- coding: utf-8 -*-
"""english_meme_final21.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F5pKRb3gvyAQRnPy9c8FnYpT1Ah-Ef03
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install torch torchvision transformers easyocr pillow pandas tqdm

import os
import torch
import pandas as pd
from PIL import Image
from tqdm import tqdm

import easyocr
from transformers import (
    BlipProcessor,
    BlipForConditionalGeneration,
    CLIPProcessor,
    CLIPModel
)

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
IMAGE_SIZE = None

print("Loading models...")
ocr_reader = easyocr.Reader(['en'], gpu=torch.cuda.is_available())
blip_processor = BlipProcessor.from_pretrained(
    "Salesforce/blip-image-captioning-large"
)
blip_model = BlipForConditionalGeneration.from_pretrained(
    "Salesforce/blip-image-captioning-large"
).to(DEVICE)

clip_processor = CLIPProcessor.from_pretrained(
    "openai/clip-vit-base-patch32"
)
clip_model = CLIPModel.from_pretrained(
    "openai/clip-vit-base-patch32"
).to(DEVICE)

CLIP_PROMPTS = [
    "a hateful meme targeting transgender people",
    "a hateful meme targeting gay or lesbian people",
    "an offensive anti lgbt meme",
    "a neutral harmless meme"
]

def load_image(path):
    img = Image.open(path).convert("RGB")
    if IMAGE_SIZE:
        img = img.resize(IMAGE_SIZE)
    return img


def extract_ocr_text(img_path):
    results = ocr_reader.readtext(img_path, detail=0)
    return " ".join(results)


def generate_caption(img):
    inputs = blip_processor(images=img, return_tensors="pt").to(DEVICE)
    out = blip_model.generate(**inputs, max_new_tokens=50)
    return blip_processor.decode(out[0], skip_special_tokens=True)


def clip_semantic_signal(img):
    inputs = clip_processor(
        text=CLIP_PROMPTS,
        images=img,
        return_tensors="pt",
        padding=True
    ).to(DEVICE)

    with torch.no_grad():
        outputs = clip_model(**inputs)
        probs = outputs.logits_per_image.softmax(dim=1)[0]

    return CLIP_PROMPTS[probs.argmax().item()]


# def cultural_reasoning_placeholder(ocr_text, caption):
#     text = (ocr_text + " " + caption).lower()

#     keywords = [
#         "should not exist",
#         "mentally ill",
#         "fake gender",
#         "only two genders",
#         "degenerate",
#         "groomer"
#     ]

#     for k in keywords:
#         if k in text:
#             return "context suggests hateful or demeaning intent"

#     return "context unclear or neutral"

IMAGE_DIR = "/content/drive/MyDrive/Train_images"
OUTPUT_CSV = "/content/drive/MyDrive/meme_project/outputs/final_fused_dataset.csv"

records = []

image_files = [
    f for f in os.listdir(IMAGE_DIR)
    if f.lower().endswith((".jpg", ".png", ".jpeg", ".webp"))
]

print(f"Processing {len(image_files)} images...")

for img_name in tqdm(image_files):
    img_path = os.path.join(IMAGE_DIR, img_name)

    try:
        img = load_image(img_path)

        ocr_text = extract_ocr_text(img_path)
        caption = generate_caption(img)
        clip_signal = clip_semantic_signal(img)
        # context_signal = cultural_reasoning_placeholder(ocr_text, caption)

        fused_text = (
            f"OCR_TEXT: {ocr_text}\n"
            f"IMAGE_CAPTION: {caption}\n"
            f"CLIP_SIGNAL: {clip_signal}\n"
            # f"CONTEXT_REASONING: {context_signal}"
        )

        records.append({
            "image_name": img_name,
            "fused_text": fused_text
        })

    except Exception as e:
        print(f"Error processing {img_name}: {e}")

df = pd.DataFrame(records)
os.makedirs(os.path.dirname(OUTPUT_CSV), exist_ok=True)
df.to_csv(OUTPUT_CSV, index=False)

print("===================================")
print(f"Final dataset saved to:\n{OUTPUT_CSV}")
print("Columns: image_name, fused_text")
print("Ready for label merge + RoBERTa training")
print("===================================")

df=pd.read_csv('/content/final_fused_dataset.csv')

df.head()

x=df.iloc[0]

x

x['fused_text']

import pandas as pd
import re

df = pd.read_csv("final_fused_dataset.csv")

# Remove extension and keep only digits
df["image_name"] = df["image_name"].astype(str).apply(
    lambda x: re.findall(r"\d+", x)[0]
)

# Optional: convert to int (recommended)
df["image_name"] = df["image_name"].astype(int)

print(df.head())

# Save back
df.to_csv("final_fused_dataset_numeric.csv", index=False)

import pandas as pd

# Read Excel file
labels_df = pd.read_excel("labels.xlsx")

# Optional: clean column names
labels_df.columns = labels_df.columns.str.strip()

# Optional: normalize text
labels_df["image_name"] = labels_df["id"].astype(str).str.strip()
labels_df["label"] = labels_df["label"].astype(str).str.lower().str.strip()

# Save as CSV
labels_df.to_csv("labels.csv", index=False)

print("labels.xlsx successfully converted to labels.csv")
print(labels_df.head())

import pandas as pd

# =============================
# PATHS
# =============================
FUSED_PATH = "final_fused_dataset_numeric.csv"
LABELS_PATH = "labels.csv"
OUTPUT_PATH = "merged_fused_labeled_dataset.csv"

# =============================
# LOAD FILES
# =============================
fused_df = pd.read_csv(FUSED_PATH)
labels_df = pd.read_csv(LABELS_PATH)

# =============================
# CLEAN + NORMALIZE
# =============================
# Ensure image_name is int in both
fused_df["image_name"] = fused_df["image_name"].astype(int)
labels_df["image_name"] = labels_df["image_name"].astype(int)

# Normalize labels
labels_df["label"] = labels_df["label"].str.lower().str.strip()

# =============================
# MERGE
# =============================
merged_df = fused_df.merge(
    labels_df[["image_name", "label"]],
    on="image_name",
    how="inner"
)

# =============================
# VERIFY
# =============================
print("Merged samples:", len(merged_df))
print("\nLabel distribution:")
print(merged_df["label"].value_counts())
print("\nSample rows:")
print(merged_df.head())

# =============================
# SAVE
# =============================
merged_df.to_csv(OUTPUT_PATH, index=False)

print("\n===================================")
print(f"FINAL DATASET SAVED: {OUTPUT_PATH}")
print("Columns: image_name | fused_text | label")
print("READY FOR EMBEDDINGS + SMOTE + 5-FOLD CV")
print("===================================")

xs=pd.read_csv("/content/merged_fused_labeled_dataset.csv")

xs.head()

pip install torch transformers scikit-learn pandas numpy matplotlib seaborn tqdm

import random
import numpy as np
import pandas as pd
import torch
from torch.utils.data import Dataset, DataLoader
from transformers import RobertaTokenizer, RobertaForSequenceClassification
from torch.optim import AdamW
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import (
    accuracy_score,
    precision_recall_fscore_support,
    confusion_matrix,
    classification_report
)
import matplotlib.pyplot as plt
import seaborn as sns
from tqdm import tqdm


DATA_PATH = "merged_fused_labeled_dataset.csv"
MODEL_NAME = "roberta-base"
EPOCHS = 3
BATCH_SIZE = 8
MAX_LEN = 256
LR = 2e-5
FOLDS = 5
SEED = 42

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"


def set_seed(seed):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)

set_seed(SEED)


df = pd.read_csv(DATA_PATH)
df["fused_text"] = df["fused_text"].astype(str)
df["label"] = df["label"].str.lower().str.strip()


le = LabelEncoder()
df["label_id"] = le.fit_transform(df["label"])
class_names = le.classes_

print("Class distribution:")
print(df["label"].value_counts())


class TextDataset(Dataset):
    def __init__(self, texts, labels, tokenizer):
        self.texts = texts
        self.labels = labels
        self.tokenizer = tokenizer

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        enc = self.tokenizer(
            self.texts[idx],
            truncation=True,
            padding="max_length",
            max_length=MAX_LEN,
            return_tensors="pt"
        )
        return {
            "input_ids": enc["input_ids"].squeeze(),
            "attention_mask": enc["attention_mask"].squeeze(),
            "labels": torch.tensor(self.labels[idx])
        }

tokenizer = RobertaTokenizer.from_pretrained(MODEL_NAME)


skf = StratifiedKFold(n_splits=FOLDS, shuffle=True, random_state=SEED)

all_fold_metrics = []
global_y_true, global_y_pred = [], []

for fold, (train_idx, val_idx) in enumerate(
    skf.split(df["fused_text"], df["label_id"]), 1
):
    print(f"\n========== FOLD {fold} ==========")

    train_ds = TextDataset(
        df.iloc[train_idx]["fused_text"].tolist(),
        df.iloc[train_idx]["label_id"].tolist(),
        tokenizer
    )
    val_ds = TextDataset(
        df.iloc[val_idx]["fused_text"].tolist(),
        df.iloc[val_idx]["label_id"].tolist(),
        tokenizer
    )

    train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True)
    val_loader = DataLoader(val_ds, batch_size=BATCH_SIZE, shuffle=False)

    model = RobertaForSequenceClassification.from_pretrained(
        MODEL_NAME, num_labels=len(class_names)
    ).to(DEVICE)

    optimizer = AdamW(model.parameters(), lr=LR)


    model.train()
    for epoch in range(EPOCHS):
        loop = tqdm(train_loader, desc=f"Epoch {epoch+1}")
        for batch in loop:
            optimizer.zero_grad()
            outputs = model(
                input_ids=batch["input_ids"].to(DEVICE),
                attention_mask=batch["attention_mask"].to(DEVICE),
                labels=batch["labels"].to(DEVICE)
            )
            loss = outputs.loss
            loss.backward()
            optimizer.step()
            loop.set_postfix(loss=loss.item())


    model.eval()
    y_true, y_pred = [], []

    with torch.no_grad():
        for batch in val_loader:
            outputs = model(
                input_ids=batch["input_ids"].to(DEVICE),
                attention_mask=batch["attention_mask"].to(DEVICE)
            )
            preds = torch.argmax(outputs.logits, dim=1)
            y_pred.extend(preds.cpu().numpy())
            y_true.extend(batch["labels"].numpy())

    global_y_true.extend(y_true)
    global_y_pred.extend(y_pred)

    acc = accuracy_score(y_true, y_pred)
    prec, rec, f1, _ = precision_recall_fscore_support(
        y_true, y_pred, average="weighted"
    )

    print(f"Accuracy : {acc:.4f}")
    print(f"Precision: {prec:.4f}")
    print(f"Recall   : {rec:.4f}")
    print(f"F1-score : {f1:.4f}")

    print("\nClassification Report:")
    print(classification_report(y_true, y_pred, target_names=class_names))


    cm = confusion_matrix(y_true, y_pred)
    plt.figure(figsize=(6, 5))
    sns.heatmap(cm, annot=True, fmt="d",
                xticklabels=class_names,
                yticklabels=class_names,
                cmap="Blues")
    plt.title(f"Confusion Matrix – Fold {fold}")
    plt.ylabel("True")
    plt.xlabel("Predicted")
    plt.show()

    all_fold_metrics.append([acc, prec, rec, f1])


metrics_df = pd.DataFrame(
    all_fold_metrics,
    columns=["Accuracy", "Precision", "Recall", "F1"]
)

print("\n========== CROSS-VALIDATION SUMMARY ==========")
print(metrics_df)
print("\nMean Metrics:")
print(metrics_df.mean())

cm_global = confusion_matrix(global_y_true, global_y_pred)
plt.figure(figsize=(6, 5))
sns.heatmap(cm_global, annot=True, fmt="d",
            xticklabels=class_names,
            yticklabels=class_names,
            cmap="Greens")
plt.title("Global Confusion Matrix (All Folds)")
plt.ylabel("True")
plt.xlabel("Predicted")
plt.show()

