# -*- coding: utf-8 -*-
"""hindi_meme.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dxqm5aBLnEFg709BwO5y3LdczMdP3NCw

HINDI-MEME CLASSIFICATION
"""

from google.colab import drive
drive.mount('/content/drive')

pip install -q transformers torch torchvision scikit-learn pandas tqdm pillow

import os, torch, pandas as pd, numpy as np
from PIL import Image
from tqdm import tqdm
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from transformers import CLIPProcessor, CLIPModel

LABEL_MAP = {
    "Homophobic": 0,
    "Transphobic": 1,
    "Non_Anti_LGBT": 2
}

class MemeDataset(Dataset):
    def __init__(self, csv_file, processor):
        self.df = pd.read_csv(csv_file)
        self.processor = processor

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]

        image_path = row["image_path"]
        text = str(row["ocr_text"])[:300]  # extra safety
        label = LABEL_MAP[row["label"].strip()]

        image = Image.open(image_path).convert("RGB")

        enc = self.processor(
            text=text,
            images=image,
            truncation=True,
            padding="max_length",
            max_length=77,
            return_tensors="pt"
        )

        return {
            "input_ids": enc["input_ids"].squeeze(0),
            "attention_mask": enc["attention_mask"].squeeze(0),
            "pixel_values": enc["pixel_values"].squeeze(0),
            "labels": torch.tensor(label)
        }

class MemeHateModel(nn.Module):
    def __init__(self, name="openai/clip-vit-base-patch32"):
        super().__init__()
        self.clip = CLIPModel.from_pretrained(name)
        dim = self.clip.config.projection_dim

        self.classifier = nn.Sequential(
            nn.Linear(dim * 2, 512),
            nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(512, 3)
        )

    def forward(self, input_ids, attention_mask, pixel_values):
        out = self.clip(
            input_ids=input_ids,
            attention_mask=attention_mask,
            pixel_values=pixel_values
        )

        fused = torch.cat([out.image_embeds, out.text_embeds], dim=1)
        return self.classifier(fused)

CSV_PATH = "/content/final_fixed_dataset.csv"

df = pd.read_csv(CSV_PATH, on_bad_lines='skip')
train_df, test_df = train_test_split(df, test_size=0.2, stratify=df["label"], random_state=42)

train_path = "/content/train.csv"
test_path = "/content/test.csv"

train_df.to_csv(train_path, index=False)
test_df.to_csv(test_path, index=False)

train_df

device = "cuda" if torch.cuda.is_available() else "cpu"

processor = CLIPProcessor.from_pretrained("openai/clip-vit-base-patch32")

train_ds = MemeDataset(train_path, processor)
test_ds  = MemeDataset(test_path, processor)

train_loader = DataLoader(train_ds, batch_size=16, shuffle=True, num_workers=2)
test_loader  = DataLoader(test_ds, batch_size=16, shuffle=False, num_workers=2)

model = MemeHateModel().to(device)
optimizer = torch.optim.AdamW(model.parameters(), lr=2e-5)
criterion = nn.CrossEntropyLoss()

EPOCHS = 12

for epoch in range(EPOCHS):
    model.train()
    total_loss = 0

    for batch in tqdm(train_loader):
        optimizer.zero_grad()

        for k in batch:
            batch[k] = batch[k].to(device)

        logits = model(
            batch["input_ids"],
            batch["attention_mask"],
            batch["pixel_values"]
        )

        loss = criterion(logits, batch["labels"])
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    print(f"\nEpoch {epoch+1} | Loss: {total_loss/len(train_loader):.4f}")

def evaluate(model, loader):
    model.eval()
    preds, gold = [], []

    with torch.no_grad():
        for batch in loader:
            for k in batch:
                batch[k] = batch[k].to(device)

            logits = model(
                batch["input_ids"],
                batch["attention_mask"],
                batch["pixel_values"]
            )

            preds.extend(torch.argmax(logits, 1).cpu().numpy())
            gold.extend(batch["labels"].cpu().numpy())

    print(classification_report(
        gold, preds,
        target_names=["Homophobic", "Transphobic", "Non_Anti_LGBT"],
        digits=4
    ))

evaluate(model, test_loader)

torch.save(model.state_dict(), "/content/drive/MyDrive/meme_project/lgbtq_meme_model_xx.pt")
print("Model saved ✅")

"""TESTING TESTING"""

def predict(image_path, text):
    model.eval()
    image = Image.open(image_path).convert("RGB")

    enc = processor(text=text, images=image, return_tensors="pt").to(device)

    with torch.no_grad():
        logits = model(**enc)

    pred = torch.argmax(logits,1).item()
    inv = {0:"homophobic",1:"transphobic",2:"non_anti_lgbt"}
    return inv[pred]

device = "cuda" if torch.cuda.is_available() else "cpu"

import torch
import torch.nn as nn
from transformers import CLIPModel

class MemeHateModel(nn.Module):
    def __init__(self, name="openai/clip-vit-base-patch32"):
        super().__init__()
        self.clip = CLIPModel.from_pretrained(name)
        dim = self.clip.config.projection_dim

        self.classifier = nn.Sequential(
            nn.Linear(dim * 2, 512),
            nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(512, 3)
        )

    def forward(self, input_ids, attention_mask, pixel_values):
        out = self.clip(
            input_ids=input_ids,
            attention_mask=attention_mask,
            pixel_values=pixel_values
        )

        fused = torch.cat([out.image_embeds, out.text_embeds], dim=1)
        return self.classifier(fused)

processor = CLIPProcessor.from_pretrained("openai/clip-vit-base-patch32")

model = MemeHateModel().to(device)
model.load_state_dict(torch.load("/content/drive/MyDrive/meme_project/lgbtq_meme_model.pt", map_location=device))
model.eval()

print("Model loaded ✅")

def predict(image_path, text):
    image = Image.open(image_path).convert("RGB")

    # safety trim
    text = str(text)[:300]

    enc = processor(
        text=text,
        images=image,
        truncation=True,
        padding="max_length",
        max_length=77,
        return_tensors="pt"
    ).to(device)

    with torch.no_grad():
        logits = model(
            enc["input_ids"],
            enc["attention_mask"],
            enc["pixel_values"]
        )

    pred = torch.argmax(logits, dim=1).item()

    inv = {0:"homophobic", 1:"transphobic", 2:"non_anti_lgbt"}
    return inv[pred]

print(predict("/content/drive/MyDrive/Train_Images/220.jpeg", "Badi shant Jahi hal Gass me MAIUON @bhi y@ bottl@ gira ke mini bbukamp laa deta be lag"))